// Copyright (c) Microsoft Corporation.  All rights reserved.
// Licensed under the MIT License.

#pragma once

// AUTO-GENERATED by WaratahCmd.exe

// HID Usage Tables: 1.4.0
// Descriptor size: 49 (bytes)
// +----------+--------+-------------------+
// | ReportId | Kind   | ReportSizeInBytes |
// +----------+--------+-------------------+
// |        1 | Input  |                 1 |
// +----------+--------+-------------------+
// |        1 | Output |                 1 |
// +----------+--------+-------------------+
// |        2 | Input  |                 1 |
// +----------+--------+-------------------+
static const uint8_t WirelessRadioControlDescriptor[] PROGMEM = 
{
    0x05, 0x01,    // UsagePage(Generic Desktop[0x0001])
    0x09, 0x0C,    // UsageId(Wireless Radio Controls[0x000C])
    0xA1, 0x01,    // Collection(Application)
    0x85, 0x01,    //     ReportId(1)
    0x09, 0xC6,    //     UsageId(Wireless Radio Button[0x00C6])
    0x15, 0x00,    //     LogicalMinimum(0)
    0x25, 0x01,    //     LogicalMaximum(1)
    0x95, 0x01,    //     ReportCount(1)
    0x75, 0x01,    //     ReportSize(1)
    0x81, 0x02,    //     Input(Data, Variable, Absolute, NoWrap, Linear, PreferredState, NoNullPosition, BitField)
    0x75, 0x07,    //     ReportSize(7)
    0x81, 0x03,    //     Input(Constant, Variable, Absolute, NoWrap, Linear, PreferredState, NoNullPosition, BitField)
    0x85, 0x02,    //     ReportId(2)
    0x09, 0xC8,    //     UsageId(Wireless Radio Slider Switch[0x00C8])
    0x75, 0x01,    //     ReportSize(1)
    0x81, 0x02,    //     Input(Data, Variable, Absolute, NoWrap, Linear, PreferredState, NoNullPosition, BitField)
    0x75, 0x07,    //     ReportSize(7)
    0x81, 0x03,    //     Input(Constant, Variable, Absolute, NoWrap, Linear, PreferredState, NoNullPosition, BitField)
    0x85, 0x01,    //     ReportId(1)
    0x09, 0xC7,    //     UsageId(Wireless Radio LED[0x00C7])
    0x75, 0x01,    //     ReportSize(1)
    0x91, 0x02,    //     Output(Data, Variable, Absolute, NoWrap, Linear, PreferredState, NoNullPosition, NonVolatile, BitField)
    0x75, 0x07,    //     ReportSize(7)
    0x91, 0x03,    //     Output(Constant, Variable, Absolute, NoWrap, Linear, PreferredState, NoNullPosition, NonVolatile, BitField)
    0xC0,          // EndCollection()
};